name: 'Azure: Deploy StreamX Medium'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/internal/azure-deploy-streamx.yaml
    with:
      environment_size: "medium"