name: 'Azure: Ingest content'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up homebrew
        uses: 'Homebrew/actions/setup-homebrew@master'

      - name: Install StreamX via Homebrew
        run: |
          brew install streamx-dev/preview-tap/streamx

      - name: "Content ingestion"
        id: streamx-content-ingestion
        env:
          STREAMX_GH_AUTH_TOKEN:
            ${{ secrets.STREAMX_GH_AUTH_TOKEN }}
        run: |
          if [ -z "$STREAMX_GH_AUTH_TOKEN" ]; then
            echo "Error: STREAMX_GH_AUTH_TOKEN is not set. Please configure the GitHub secret."
            exit 1
          fi

          github_token=$(echo "$STREAMX_GH_AUTH_TOKEN" | yq e '.data.jwt' - | base64 --decode)
          echo "%github.streamx.ingestion.auth-token=$github_token" >> .env
          terraform/scripts/cloud-publish-all.sh